// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerwaltungSchuelerdaten.Data;

namespace VerwaltungSchuelerdaten.Migrations
{
    [DbContext(typeof(VerwaltungSchuelerdatenContext))]
    [Migration("20210222091209_linkSchuelerKlasse")]
    partial class linkSchuelerKlasse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VerwaltungSchuelerdaten.Models.Klasse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlassenSprecherInID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KlassenSprecherInID");

                    b.ToTable("Klasse");
                });

            modelBuilder.Entity("VerwaltungSchuelerdaten.Models.SchuelerDaten", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Anmeldedatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Geburtsdatum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KlasseID")
                        .HasColumnType("int");

                    b.Property<string>("Kommentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konfession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staatsangehoerigkeit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZweiteStaatsangehoerigkeit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KlasseID");

                    b.ToTable("SchuelerDaten");
                });

            modelBuilder.Entity("VerwaltungSchuelerdaten.Models.Klasse", b =>
                {
                    b.HasOne("VerwaltungSchuelerdaten.Models.SchuelerDaten", "KlassenSprecherIn")
                        .WithMany()
                        .HasForeignKey("KlassenSprecherInID");
                });

            modelBuilder.Entity("VerwaltungSchuelerdaten.Models.SchuelerDaten", b =>
                {
                    b.HasOne("VerwaltungSchuelerdaten.Models.Klasse", "Klasse")
                        .WithMany("Schueler")
                        .HasForeignKey("KlasseID");
                });
#pragma warning restore 612, 618
        }
    }
}
